# Generated by Django 4.1.7 on 2023-02-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('slider_img', models.ImageField(upload_to='slider_imgs/', verbose_name='Картинка')),
                ('slider_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slider_desr', models.TextField(max_length=500, verbose_name='Описание')),
                ('slider_css', models.CharField(default='-', max_length=20, verbose_name='Активный слайд')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
