# Generated by Django 4.1.7 on 2023-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_id_alter_cmsslider_slider_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderCms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(default='-', null=True, upload_to='slider_imgs', verbose_name='Картинка')),
                ('slider_title', models.CharField(default='-', max_length=200, null=True, verbose_name='Заголовок')),
                ('slider_desr', models.CharField(default='-', max_length=200, null=True, verbose_name='Описание')),
                ('slider_css', models.CharField(default='-', max_length=20, null=True, verbose_name='Активный слайд')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.DeleteModel(
            name='CmsSlider',
        ),
    ]
